### PR TITLE
add bufferToVideo and fetchVideo

### PR DESCRIPTION
**Pull request by lpsBetty**
Solving a few issues from the original repository:

* https://github.com/justadudewhohacks/face-api.js/issues/392
* https://github.com/justadudewhohacks/face-api.js/issues/664

### CODE REVIEW

**Comment by vladmandic** [comment]
thank you for the contribution!  

can you exclude all items in diff from `/dist` and `/types` as those are generated by the build process?  
only items in `/src` should be modified  

when ready, i'll review the diff (and pending few tests) and push a new update

**Comment by lpsBetty** [comment]
@vladmandic i have overwritten the previous commit and removed the files in `dist` and `types`. Additionally added 1 commit to fix loading quicktime videos.

**Comment by vladmandic** [comment]
Couple of quick comments:

in `src/env/createNodejsEnv.ts`: 
```js
const Video = global['Video'] || global.HTMLVideoElement;
```

What is a possible implementation of `Video` for NodeJS?  
Or is this just a placeholder for some "possible" implementation?  
E.g., for Canvas there is a Canvas library that performs required functionality  

in `src/dom/bufferToVideo.ts`:
```js
video.onerror = reject;
```
Did you test if onerror passes error paramter to promise reject?  
If not, it should be specified expicitly, something like:
```js
video.onerror = (error) => reject(new Error(error));
```

And this is a bad idea in most cases as we don't know how long load is going to take  
```js
video.onloadstart = () => {
  setTimeout(() => resolve(video), 100);
};

If using timeouts, then check for `video.readyState >= 2` which means there is sufficient data for at least one frame  
or alternatively try using `video.onloadeddata` or `video.oncanplay`

**Comment by lpsBetty** [comment]
> Couple of quick comments:
> 
> in `src/env/createNodejsEnv.ts`:
> 
> ```js
> const Video = global['Video'] || global.HTMLVideoElement;
> ```
> 
> What is a possible implementation of `Video` for NodeJS?
> Or is this just a placeholder for some "possible" implementation?

Yes it is just a placeholder!

> in `src/dom/bufferToVideo.ts`:
> 
> ```js
> video.onerror = reject;
> ```
> 
> Did you test if onerror passes error paramter to promise reject?

It returns a HTMLMediaError as described here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/error

> And it's a bad idea in most cases to hard-code timeout values as we don't know how long load is going to take
> 
> ```js
> video.onloadstart = () => {
>   setTimeout(() => resolve(video), 100);
> };
> ```
> 
> If using timeouts, then check for `video.readyState >= 2` which means there is sufficient data for at least one frame
> or alternatively try using `video.onloadeddata` or `video.oncanplay`

You are right, i just copied this part from https://github.com/justadudewhohacks/face-api.js/issues/392  - i just changed it to `oncanplay`, makes total sense!

Thanks for the feedback!

**Comment by lpsBetty** [comment]
@vladmandic i am so sorry, i just found another bug when using the face expression detection - every frame returned "neutral 0.99", so i need to change `video.autoplay = true` to `video.play()` - i don't know why it doesn't work with autoplay, but the code for the webcam also uses `play()`, so i think it is save to use it here as well, i already tested locally and then i got other expressions as well :) 

I will make another PR :/

**Pull request merged**
