### PR TITLE
Fixed bug which led to latency not being measured in multiprocess node demo

### PR DESCRIPTION
**Pull request by mayankagarwals**
Thank you for providing an updated version of face-api.js :)

Fixed a small bug that was printing wrong metrics on the console.

### CODE REVIEW

**Comment by vladmandic** [comment]
you're welcome - and thanks for the PR, it's a good catch on number of images to process.

**Comment by mayankagarwals** [comment]
Hey, I had a small query and didn't want to create an issue just for that. 

Considering that I want to implement this is in an only CPU environment, do you think the nodejs multiprocess implementation is the fastest performance (or near fastest) possible while keeping a comparable lfw benchmark. 

I did some research and it looks like for the three subtasks, the best detector available is MTCNN, the best landmark predictor is by dlib and the best recognizer is mobilefacenet. If that information is useful

Would like to hear your opinions on it!. Thanks :)

**Comment by vladmandic** [comment]
> Considering that I want to implement this is in an only CPU environment, do you think the nodejs multiprocess implementation is the fastest performance (or near fastest) possible while keeping a comparable lfw benchmark.

Yes, I don't see any better options  

Note that TFJS 3.4.0 was just released and finally `tfjs-node` is based on tensorflow lib 2.4, not old 1.1  
There are still some bugs in TFJS 3.4.0, but as soon as that is resolved, I'll publish new version and that should result in some gains  

> I did some research and it looks like for the three subtasks, the best detector available is MTCNN, the best landmark predictor is by dlib and the best recognizer is mobilefacenet.

Based on what metrics? I find MTCNN detector much slower than SSD and results are comparable. DLIB landmarks are ok for small number of points, but far from best landmark predictor and I had poor results with MobileFaceNet recognizer and I've recently switched to HSE FaceRec (although I'm not done investigating best options here) in my newer project <https://github.com/vladmandic/human>

> On my intel i5 8th gen processor with 8 gb ram, I was able to calculate encodings (just the detection, landmarks and recognition) for 6 frames in ~1.1s using 4 child processes.

I'll run some benchmarks on my side and update here

**Comment by mayankagarwals** [comment]
> Yes, I don't see any better options

Yeah. So just for educational purposes, from my understanding, Tensorflow does parallelization on its own too but all the executions which are not TensorFlow related would still run on a single core if a single instance of node is run as a single instance. On increasing the parallelism, these operations also happen on different cores. So once can't expect a linear increase in speedup. Correct? I was able to bring down the time taken to process 6 frames from 1.5 s to 1.1 s by adding parallelization. 

> Based on what metrics?
Some kaggle comparison (https://www.kaggle.com/timesler/comparison-of-face-detection-packages#706137 ) although the ssd mobilenet model used here isn't compared there.  It wasn't research really, sorry for the poor framing of words

Also, can you point me to what is the source of the landmark detection model used here. The original repo doesn't specify. 

> Note that TFJS 3.4.0 was just released and finally `tfjs-node` is based on tensorflow lib 2.4, not old 1.1
> There are still some bugs in TFJS 3.4.0, but as soon as that is resolved, I'll publish new version and that should result in some gains

That'd be great! I'm actually just a student so all of this is my first try in the nodeJS world. Never thought the best face recognition model would be implemented in nodejs. Was thinking it would be available as a python module :p

Okay, I think this makes sense. So just to be clear, according to your findings, here are the best options for face recognition algorithms currently regardless of language
1. Face Detection - ssd mobilenet
2. Face Landmark - (Insert the one used here)
3. Face Recognition - Yet to be investigated, for now, HSE_REC

**Comment by vladmandic** [comment]
> Tensorflow does parallelization on its own too 

Yes, but some kernel ops inside model can be run in parallel - so it depends on model architecture. Some models are optimized for parallel execution, some are mostly sequential.

> but all the executions which are not TensorFlow related would still run on a single core if a single instance of node is run.

Correct.

> Some kaggle comparison 

That article compares very oooold models.
If I had to put my money down for pure quality, it would be something like ArcFace/InsightFace <https://github.com/deepinsight/insightface>

> Never thought the best face recognition model would be implemented in nodejs. Was thinking it would be available as a python module

Most models are implemented in Python, but then during training they are frozen at time when author determines results are good enough (typically after n epochs of training when results start to converge) resulting in TF Frozen Model.
Then you optimize it by removing all the excess from weights and compile to TF Saved Model.
Optionally, you quantize the model to use Float32/Float16/Uint64/Uint32/Uint16/Uint8 - and that compresses the weights even more.  
Then you convert to whatever you want to use, in case of TFJS, its TFJS Graph Model.
And that is just the case for TensorFlow. If model is trained using different ML framework, format of the compiled model will be very different, but most likely it can still be converted somehow :)

Also, note that in case of Tensorflow, both Python and NodeJS use the same implementation - binary tensorflow.so library. Python and NodeJS are just front-end languages to interface with the library as you probably don't want to use C++ for that :)

So what you use for definition and training and what you use for inference doesn't matter.

> So just to be clear, according to your findings, here are the best options for face recognition algorithms currently regardless of language

A bit of background - first thing I did was modernize FaceAPI as I wanted to use it in my other projects. But then I figured out its based on quite an old models and that's why I started my newer project `Human`: <https://github.com/vladmandic/human> with goal to use whatever the best models are - with constraints of size. I don't want to use 100MB+ model just for detection.

**Comment by vladmandic** [comment]
This conversation prompted me to write a quick benchmark, here are initial results:

Using tensorflow backend (CPU execution using libtensorflow), I'll try later with CUDA-accelerated backend

In most cases CPU will be fully saturated with 4 workers with 80% user-mode and 20% system meaning waiting for I/O such as reading actual images

System: i5-6500TE; 4 Cores @ 2.30GHz
Enabled: Detection, Landmarks, Age, Gender, Emotion, Descriptor
FaceAPI: Processed: 69 images in total: 43896 ms working: 42559 ms average: 616 ms
Human: Processed: 69 images in total: 24846 ms working: 23706 ms average: 343 ms

System: i5-6500TE; 4 Cores @ 2.30GHz
Enabled: Detection, Landmarks
FaceAPI: Processed: 69 images in total: 38357 ms working: 37190 ms average: 538 ms
Human: Processed: 69 images in total: 19091 ms working: 18172 ms average: 263 ms

System: i5-6500TE; 12 Cores @ 2.20GHz
Enabled: Detection, Landmarks, Age, Gender, Emotion, Descriptor
FaceAPI: Processed: 69 images in total: 13176 ms working: 12613 ms average: 182 ms
Human: Processed: 69 images in total: 10038 ms working: 9315 ms average: 135 ms

So Human is ~2x faster than FaceAPI with much higher level of details  
(for example, FaceAPI has 68-point landmarks while Human has 468-points and FaceAPI uses 128-element descriptor while Human uses 1024-element descriptor)  
That's what couple of years of development do in ML world :)

And in video processing, difference is even higher since FaceAPI processes each frame independently while Human has aggressive caching between frames

**Comment by mayankagarwals** [comment]
> Yes, but some kernel ops inside model can be run in parallel - so it depends on model architecture. Some models are optimized for parallel execution, some are mostly sequential

> And that is just the case for TensorFlow. If model is trained using different ML framework, format of the compiled model will be very different, but most likely it can still be converted somehow :)

Yes, makes sense. Thanks a lot for this :)

> So Human is ~2x faster than FaceAPI with much higher level of details
> (for example, FaceAPI has 68-point landmarks while Human has 468-points and FaceAPI uses 128-element descriptor while Human uses 1024-element descriptor)
> That's what couple of years of development do in ML world :)

That is really awesome! I'll definitely checkout human in the coming week, looks very interesting! Haha yes, fast paced world :)

**Pull request merged**
